type Customer {
  id: ID!
  name: String!
  email: String!
}

type Product {
  id: ID!
  name: String!
  price: Float!
  description: String!
  image: String!
}

type Query {
  customers: [Customer!]!
  customer(id: ID!): Customer
  products: [Product!]!
  product(id: ID!): Product
}

type Mutation {
  createProduct(
    name: String!
    price: Float!
    description: String!
    image: String!
  ): Product!
  updateProduct(
    id: ID!
    name: String
    price: Float
    description: String
    image: String
  ): Product!
  deleteProduct(id: ID!): Product!
}

schema {
  query: Query
  mutation: Mutation
}
